language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
node_js:
  - 8.10.0
  - 10.15.0
dist: trusty
addons:
  chrome: stable
before_script:
  - npm install -g codecov nyc
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build --debug

script:
  - yarn lint
  - yarn audit
  - nyc --reporter=lcov yarn cover

after_script:
  - ./cc-test-reporter format-coverage --output "coverage/codeclimate.$N.json" --debug
  - ./cc-test-reporter upload-coverage --debug
  - ./cc-test-reporter after-build --exit-code --debug $TRAVIS_TEST_RESULT
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov -f coverage/lcov.info --disable=gcov

notifications:
  slack:
    rooms:
      - ninjaro:clZjvDamAByBYA004CYcYlH6#build
    on_success: always
    on_failure: always
